'use server';

/**
 * @fileOverview Image Tagging with Computer Vision AI agent.
 *
 * - tagProductImagesWithCV - A function that handles the product image tagging process.
 * - TagProductImagesWithCVInput - The input type for the tagProductImagesWithCV function.
 * - TagProductImagesWithCVOutput - The return type for the tagProductImagesWithCV function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TagProductImagesWithCVInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of a product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'  
    ),
});
export type TagProductImagesWithCVInput = z.infer<typeof TagProductImagesWithCVInputSchema>;

const TagProductImagesWithCVOutputSchema = z.object({
  tags_cv: z.array(z.string()).describe('Tags generated by computer vision.'),
  dominant_colors: z.array(z.string()).describe('Dominant colors extracted from the image.'),
});
export type TagProductImagesWithCVOutput = z.infer<typeof TagProductImagesWithCVOutputSchema>;

export async function tagProductImagesWithCV(input: TagProductImagesWithCVInput): Promise<TagProductImagesWithCVOutput> {
  return tagProductImagesWithCVFlow(input);
}

const tagProductImagesWithCVPrompt = ai.definePrompt({
  name: 'tagProductImagesWithCVPrompt',
  input: {schema: TagProductImagesWithCVInputSchema},
  output: {schema: TagProductImagesWithCVOutputSchema},
  prompt: `You are a computer vision expert. Analyze the image and extract relevant tags and dominant colors.

  Output the tags_cv field as an array of strings describing the image.
  Output the dominant_colors field as an array of strings representing the hex codes of the dominant colors.

  Image: {{media url=photoDataUri}}
  `,
});

const tagProductImagesWithCVFlow = ai.defineFlow(
  {
    name: 'tagProductImagesWithCVFlow',
    inputSchema: TagProductImagesWithCVInputSchema,
    outputSchema: TagProductImagesWithCVOutputSchema,
  },
  async input => {
    const {output} = await tagProductImagesWithCVPrompt(input);
    return output!;
  }
);
