'use server';

/**
 * @fileOverview Image Tagging with Computer Vision AI agent.
 *
 * - tagProductImages - A function that handles the product image tagging process.
 * - TagProductImagesInput - The input type for the tagProductImages function.
 * - TagProductImagesOutput - The return type for the tagProductImages function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TagProductImagesInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of a product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'  
    ),
});
export type TagProductImagesInput = z.infer<typeof TagProductImagesInputSchema>;

const TagProductImagesOutputSchema = z.object({
  tags_cv: z.array(z.string()).describe('Tags generated by computer vision.'),
  dominant_colors: z.array(z.string()).describe('Dominant colors extracted from the image.'),
});
export type TagProductImagesOutput = z.infer<typeof TagProductImagesOutputSchema>;

export async function tagProductImages(input: TagProductImagesInput): Promise<TagProductImagesOutput> {
  return tagProductImagesFlow(input);
}

const tagProductImagesPrompt = ai.definePrompt({
  name: 'tagProductImagesPrompt',
  input: {schema: TagProductImagesInputSchema},
  output: {schema: TagProductImagesOutputSchema},
  prompt: `You are a computer vision expert. Analyze the image and extract relevant tags and dominant colors.

  Output the tags_cv field as an array of strings describing the image.
  Output the dominant_colors field as an array of strings representing the hex codes of the dominant colors.

  Image: {{media url=photoDataUri}}
  `,
});

const tagProductImagesFlow = ai.defineFlow(
  {
    name: 'tagProductImagesFlow',
    inputSchema: TagProductImagesInputSchema,
    outputSchema: TagProductImagesOutputSchema,
  },
  async input => {
    const {output} = await tagProductImagesPrompt(input);
    return output!;
  }
);
